# Generated by Django 4.2.6 on 2023-12-06 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exploitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('post_nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('etat_civil', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve')], max_length=20)),
                ('nom_conjoint', models.CharField(blank=True, max_length=255, null=True)),
                ('nb_enfants', models.PositiveIntegerField(default=0)),
                ('adresse', models.CharField(max_length=500)),
                ('niveau_etude', models.CharField(choices=[('Aucun', 'Aucun'), ('Primaire', 'Primaire'), ('Secondaire', 'Secondaire'), ("Diplômé(e) d'Etat", "Diplômé(e) d'Etat"), ('Gradué(e)', 'Gradué(e)'), ('Licencié(e)', 'Licencié(e)'), ('Ingénieur(e)', 'Ingénieur(e)'), ('Docteur', 'Docteur'), ('Autre', 'Autre')], max_length=50)),
                ('profession', models.CharField(max_length=255)),
                ('fonction', models.CharField(choices=[('Creuseur', 'Creuseur'), ('Constructeur', 'Constructeur'), ('Agent Mobile', 'Agent Mobile'), ('Agent de Sécurité', 'Agent de Sécurité'), ('Membre du Comité', 'Membre du Comité'), ('Membre de la Coopérative', 'Membre de la Coopérative'), ('Laveuse', 'Laveuse'), ('Négociant', 'Négociant'), ('Sponsor', 'Sponsor'), ('Cleaner', 'Cleaner'), ('Agent de Bureau', 'Agent de Bureau')], max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_mise_a_jour', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
    ]
