# Generated by Django 4.2.6 on 2023-12-13 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incident', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(max_length=500)),
                ('type_incident', models.CharField(choices=[('Mortel', 'Mortel'), ('Non-mortel', 'Non-mortel')], max_length=50)),
                ('Nombre_cas', models.IntegerField()),
                ('Noms_accidentes', models.CharField(max_length=500)),
                ('cause_incident', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('rapporteur', models.CharField(max_length=500)),
                ('proprietaire', models.CharField(max_length=500)),
                ('actions', models.CharField(max_length=1000)),
            ],
        ),
    ]
